# Generated by Django 5.0.7 on 2024-08-09 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0012_alter_metrics_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=9)),
                ("percentual", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AS", "Awaiting signature"),
                            ("PE", "Proposal sent"),
                            ("PA", "Proposal accepted"),
                            ("PR", "Proposal rejected"),
                        ],
                        default="AS",
                        max_length=2,
                    ),
                ),
                (
                    "selfie",
                    models.FileField(blank=True, null=True, upload_to="selfies"),
                ),
                ("rg", models.FileField(blank=True, null=True, upload_to="rgs")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="companies.company",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
