# Generated by Django 5.0.7 on 2024-08-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentproposal",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
