# Generated by Django 5.1 on 2024-08-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investors", "0003_remove_investmentproposal_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentproposal",
            name="proposal_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, unique=True
            ),
        ),
    ]
