# Generated by Django 5.1 on 2024-08-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investors", "0004_investmentproposal_proposal_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentproposal",
            name="proposal_token",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
