# Generated by Django 5.0.7 on 2024-08-05 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("cnpj", models.CharField(max_length=30)),
                ("site", models.URLField()),
                (
                    "existence_time",
                    models.CharField(
                        choices=[
                            ("-6", "Menos de 6 meses"),
                            ("+6", "Mais de 6 meses"),
                            ("+1", "Mais de 1 ano"),
                            ("+5", "Mais de 5 anos"),
                        ],
                        default="-6",
                        max_length=2,
                    ),
                ),
                ("desc", models.TextField()),
                ("last_date_caption", models.DateField()),
                ("percentual_equity", models.IntegerField()),
                (
                    "internship",
                    models.CharField(
                        choices=[
                            ("I", "Tenho apenas uma idea"),
                            ("MVP", "Possuo um MVP"),
                            ("MVPP", "Possuo um MVP com clientes pagantes"),
                            ("E", "Empresa pronta para escalar"),
                        ],
                        default="I",
                        max_length=4,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("ED", "Ed-tech"),
                            ("FT", "Fintech"),
                            ("AT", "Agrotech"),
                        ],
                        max_length=3,
                    ),
                ),
                ("targe_audience", models.CharField(max_length=3)),
                ("value", models.DecimalField(decimal_places=2, max_digits=9)),
                ("pitch", models.FileField(upload_to="pitches")),
                ("logo", models.FileField(upload_to="videos")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
