# Generated by Django 5.0.7 on 2024-08-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="desc",
            new_name="description",
        ),
    ]
