# Generated by Django 5.0.7 on 2024-08-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_rename_desc_company_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="existence_time",
            field=models.CharField(
                choices=[
                    ("-6", "less than 6 months"),
                    ("+6", "more than 6 months"),
                    ("+1", "more than 1 year"),
                    ("+5", "more than 5 year"),
                ],
                default="-6",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="internship",
            field=models.CharField(
                choices=[
                    ("I", "I just have an ideia"),
                    ("MVP", "I've a MVP"),
                    ("MVPP", "I've a MVP with clients"),
                    ("E", "Companies ready to scale"),
                ],
                default="I",
                max_length=4,
            ),
        ),
    ]
