# Generated by Django 5.0.7 on 2024-08-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_company_existence_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="targe_audience",
        ),
        migrations.AddField(
            model_name="company",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("BTC", "Business to Consumer"),
                    ("Business to Business", "B2B"),
                ],
                default="BTC",
                max_length=20,
            ),
        ),
    ]
