# Generated by Django 5.0.7 on 2024-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_remove_company_targe_audience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("BTC", "Business to Consumer"),
                    ("B2B", "Business to Business"),
                ],
                default="BTC",
                max_length=20,
            ),
        ),
    ]
