# Generated by Django 5.0.7 on 2024-08-06 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_alter_company_target_audience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="last_date_caption",
            new_name="last_date_capture",
        ),
    ]
