# Generated by Django 5.0.7 on 2024-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_rename_last_date_caption_company_last_date_capture"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
