# Generated by Django 5.0.7 on 2024-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_company_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
