# Generated by Django 5.0.7 on 2024-08-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0009_alter_company_logo_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("document", models.FileField(upload_to="documents")),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
